# Generated by Django 2.2 on 2019-04-07 04:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(max_length=500, verbose_name='Descrição')),
                ('video_file', models.FileField(upload_to='', verbose_name='Arquivo de vídeo')),
                ('video_thumb', models.ImageField(upload_to='', verbose_name='Capa do vídeo')),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Upload feito em')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.Channel')),
            ],
        ),
    ]
