# Generated by Django 2.2 on 2019-04-07 04:44

import apps.videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20190407_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=apps.videos.models.video_path, verbose_name='Arquivo de vídeo'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_thumb',
            field=models.ImageField(upload_to=apps.videos.models.thumb_path, verbose_name='Capa do vídeo'),
        ),
    ]
